### ISSUE TITLE
ES6 Babel transpiling issue with /*@ngInject*/

### ISSUE THREAD

**Issue by m3fawner** [olov/ng-annotate#184]
I have implemented classes in a way that allows me to continue to have variables/functions scoped to the class, and the class only, and that's causing ngAnnotate issues. I have my controllers declared as such in the source:

```javascript
'use strict';
let AppCtrl;
(() => {
    let vm, UserProfile, ModalService, ErrorService;
    AppCtrl = class {
        /*@ngInject*/
        constructor(_UserProfile_, _ModalService_, _ErrorService_) {
            vm = this;
            [UserProfile, ModalService, ErrorService] = arguments;
            init();

            function init() {
                vm.openMarketingModal = ModalService.openMarketingModal;
                vm.errors = ErrorService.errors;
                vm.whiteList = ['/cmc-rest/', '/myu/', '/ebz/'];
                vm.supportedLanguages = [{
                    label: 'English',
                    locale: 'en_US'
                }, {
                    label: 'Español',
                    locale: 'es_ES'
                }];
                vm.selectedLanguage = vm.supportedLanguages[0];
                UserProfile.getUserProfile()
                    .then((data) => {
                              vm.userData = data;
                    });
            }
        }
    };
})();
angular.module('myApp')
    .controller('AppCtrl', AppCtrl);
```

From what I've seen, the /*@ngInject*/ comment goes where I have it (just above the constructor). When it gets transpiled into ES5 using babel, we get the following:

```javascript
'use strict';
var _slice = Array.prototype.slice;

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError('Cannot call a class as a function'); } }

var AppCtrl = undefined;
(function () {
    var vm = undefined,
        UserProfile = undefined,
        ModalService = undefined,
        ErrorService = undefined;
    AppCtrl = (function () {
        /*@ngInject*/

        function _class(_UserProfile_, _ModalService_, _ErrorService_) {
            _classCallCheck(this, _class);

            vm = this;

            var _arguments = _slice.call(arguments);

            UserProfile = _arguments[0];
            ModalService = _arguments[1];
            ErrorService = _arguments[2];

            init();

            function init() {
                vm.openMarketingModal = ModalService.openMarketingModal;
                vm.errors = ErrorService.errors;
                vm.whiteList = ['/cmc-rest/', '/myu/', '/ebz/'];
                vm.supportedLanguages = [{
                    label: 'English',
                    locale: 'en_US'
                }, {
                    label: 'Español',
                    locale: 'es_ES'
                }];
                vm.selectedLanguage = vm.supportedLanguages[0];
                UserProfile.getUserProfile().then(function (data) {
                   vm.userData = data;
                });
            }
        }

        return _class;
    })();
})();
angular.module('myApp').controller('AppCtrl', AppCtrl);
//# sourceMappingURL=app.controller.es5.js.map
```

As you can see, the comment is in the correct spot still, but I get the following from my ngAnnotate task:
```
Generating "target/src/app/app.controller.es5.js" from: "target/src/app/app.controller.es5.js"...ERROR
>> error: TypeError: Cannot read property 'type' of undefined
Warning: Task "ngAnnotate:target" failed. Use --force to continue.

Aborted due to warnings.
```

If I rewrite the same class to look as such:

```javascript
'use strict';
let vm, UserProfile, ModalService, ErrorService;
class AppCtrl {
    /*@ngInject*/
    constructor(_UserProfile_, _ModalService_, _ErrorService_) {
        vm = this;
        [UserProfile, ModalService, ErrorService] = arguments;
        init();

        function init() {
            vm.openMarketingModal = ModalService.openMarketingModal;
            vm.errors = ErrorService.errors;
            vm.whiteList = ['/cmc-rest/', '/myu/', '/ebz/'];
            vm.supportedLanguages = [{
                label: 'English',
                locale: 'en_US'
            }, {
                label: 'Español',
                locale: 'es_ES'
            }];
            vm.selectedLanguage = vm.supportedLanguages[0];
            UserProfile.getUserProfile()
                .then((data) => {
                     vm.userData = data;
                });
        }
    }
}
angular.module('myApp')
    .controller('AppCtrl', AppCtrl);
```

Everything works fine, transpiling and ngAnnotate included. Any help would be extremely appreciated!

**Comment by olov** [comment]
Thanks for your test case. This is a bug, ng-annotate should not crash that way on any input code. I'll look into it.

**Comment by olov** [comment]
fixed in 1.0.2

**Comment by m3fawner** [comment]
I am still receiving the same error as before, using version 1.0.2:

```
Generating "target/src/app/app.controller.es5.js" from: "target/src/app/app.controller.es5.js"...ERROR
>> error: TypeError: Cannot read property 'type' of undefined
Warning: Task "ngAnnotate:target" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by olov** [comment]
I'll take another look on this

**Comment by olov** [comment]
@m3fawner I need more info on this. Can you isolate the test case to a separate file and run it using `ng-annotate -a filename` (first `npm install -g ng-annotate`)? Thanks

**Comment by m3fawner** [comment]
```javascript
'use strict';
var _slice = Array.prototype.slice;

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError('Cannot call a class as a function'); } }

var A = undefined;
(function () {
        var _SomeDependency = undefined;
        A = (function () {
                /*@ngInject*/

                function _class(SomeDependency) {
                        _classCallCheck(this, _class);

                        var _arguments = _slice.call(arguments);

                        _SomeDependency = _arguments[0];
                }
                _class.$inject = ["SomeDependency"];

                return _class;
        })();
})();
//# sourceMappingURL=test.es5.js.map
```
It seems to have worked in this instance.

**Comment by m3fawner** [comment]
Ok, so I found that if I run ng-annotate -a app.controller.js, I don't have any issues and it outputs correctly:

```javascript
'use strict';
var _slice = Array.prototype.slice;

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError('Cannot call a class as a function'); } }

var AppCtrl = undefined;
(function () {
    var _ModalService = undefined,
        _ErrorService = undefined,
        _UserService = undefined;
    AppCtrl = (function () {
        /*@ngInject*/

        function _class(ModalService, ErrorService, UserService) {
            var _this = this;

            _classCallCheck(this, _class);

            var _arguments = _slice.call(arguments);

            _ModalService = _arguments[0];
            _ErrorService = _arguments[1];
            _UserService = _arguments[2];

            var supportedLanguages = [{
                label: 'English',
                locale: 'en-US'
            }, {
                label: 'Español',
                locale: 'es-ES'
            }],
                marketingImageConfig = [{
                locale: 'en-US',
                imgSrc: 'assets/portal-ad.svg',
                hoverSrc: 'assets/portal-ad-hover.svg'
            }, {
                locale: 'es-ES',
                imgSrc: 'assets/portal-ad-spanish.svg',
                hoverSrc: 'assets/portal-ad-spanish-hover.svg'
            }];
            _UserService.getUserInformation().then(function (response) {
                var commodities = Array.from(response.contactInformation.businessInformation.additionalBusinessGroups);
                commodities.push(response.contactInformation.businessInformation.primaryBusinessGroup);
                _this.commodities = commodities;
            });
            Object.assign(this, {
                openMarketingModal: ModalService.openMarketingModal,
                errors: ErrorService.errors,
                whiteList: ['/cmc-rest/', '/myu/', '/cpt-service/'],
                supportedLanguages: supportedLanguages,
                marketingImageConfig: marketingImageConfig,
                selectedLanguage: supportedLanguages[0]
            });
        }
        _class.$inject = ["ModalService", "ErrorService", "UserService"];

        return _class;
    })();
})();
angular.module('myuprr').controller('AppCtrl', AppCtrl);
//# sourceMappingURL=app.controller.es5.js.map
```

but if I run the grunt task ngAnnotate, I get the following:

```
Running "ngAnnotate:target" (ngAnnotate) task
Generating "src/app/app.controller.es5.js" from: "target/src/app/app.controller.es5.js"...ERROR
>> error: TypeError: Cannot read property 'type' of undefined
Warning: Task "ngAnnotate:target" failed. Use --force to continue.
```

My grunt task looks as such:

```javascript
'use strict';

/**
 * `ng-annotate` annotates the sources before minifying. That is, it allows us to code without the array syntax.
 */
module.exports = {
    options: {
        sourceMap: true
    },
    target: {
        cwd: '<%= buildConfig.buildDir %>/',
        src: ['**/app.controller.es5.js'],
        expand: true,
        dest: ''
    }
};
```

**Comment by olov** [comment]
which version of grunt-ngannotate do you have installed? also, peek around inside its node_modules to find what version of  ng-annotate it did install.

**Comment by m3fawner** [comment]
1.0.2 in both instances

**Comment by olov** [comment]
Hmm. Try removing sourcemap-generation to see if it makes a difference (it shouldn't). @mzgol can you think of anything?

**Comment by m3fawner** [comment]
Oops, 1.0.1 for ng-annotate. It appears 1.0.2 isn't a valid version (I had it in package, but after a cache clean found it to be an invalid version).

I removed the sourcemap-generation and saw several of the classes correctly injected. It appears to have solved the issue, though I will confirm tomorrow. I have a few that are failing to find providers, but that may be due to my notation.

**Comment by olov** [comment]
grunt-ng-annotate 1.0.1 is fine but you need to make sure that you've installed or upgraded it recently, because grunt-ng-annotate as of 1.0.1 depends on `ng-annotate ^1.0.1`. Check out grunt-ng-annotate/node_modules/ng-annotate/package.json to see which version of ng-annotate it uses. From your problem description, it looks like you're still using an old version of ng-annotate. The issue was fixed in 1.0.2.

**Comment by m3fawner** [comment]
Ah, grunt-ng-annotate 1.0.1 is using 1.0.0 for the project I'm testing on. I replaced ng-annotate with 1.0.2 and it seemed to have worked. Thanks, Olov. Are we going to have a 1.0.2 released that would have this problem of an old dependency fixed?

**Comment by mzgol** [comment]
@m3fawner grunt-ng-annotate `1.0.1` doesn't depend on ng-annotate `1.0.0` but `^1.0.0`. There is no need for a new release, @olov already described how it works. Just reinstall `grunt-ng-annotate` and you'll get a new version.

**Comment by m3fawner** [comment]
Is this supposed to fix the sourcemap portion of it? I reinstalled and got
```
Warning: SourceMapGenerator.prototype.applySourceMap requires either an explicit source file, or the source map's "file" property. Both were omitted. Use --force to continue.
```
but that was with 1.0.2
